### ISSUE TITLE
When I Shift-grab several groups and the elements within, and try to move them, they move at different speeds

### ISSUE THREAD

**Issue by thisisandrea** [ciudadanointeligente/vizard#178]
...the elements move faster, and gradually start to separate from their groups. See below. (In Chrome)
![screen shot 2014-12-29 at 3 31 17 pm](https://cloud.githubusercontent.com/assets/9385601/5573678/30d7621a-8f7e-11e4-934d-e28e840ffb00.png)
![screen shot 2014-12-29 at 3 31 08 pm](https://cloud.githubusercontent.com/assets/9385601/5573679/34f2f274-8f7e-11e4-8913-617619877e61.png)

**Comment by jdgarrido** [comment]
hi @thisisandrea 
when you need to move grouped elements, you only need to select the groupOrganization boxes, not all the elements. For instance, in this case use the ctrl or cmd button for selecting the five groupOrganizations and moving them along with their embedded elements.
