### ISSUE TITLE
Fix usability issues for stencil (left hand menu)

### ISSUE THREAD

**Issue by maugsbur** [ciudadanointeligente/vizard#232]
- Make the stencil smaller, making it grow when on hover
- Add border to groups in order to make it visible
- Add separators and labels to elements, like
![image](https://cloud.githubusercontent.com/assets/1598495/6419906/0fdd7daa-bea0-11e4-8d88-eb54cfa03fee.png)

**Comment by marceloperez** [comment]
Se dividió en 3 issues especificos
