### ISSUE TITLE
Stage 1 - policy problem add and edit buttons aren't clear

### ISSUE THREAD

**Issue by maugsbur** [ciudadanointeligente/vizard#377]
- The colors don't seem consistent
- The position of the edit button on a policy problem looks awkward
- It isn't clear that the add button for policy problem is for adding a policy problem (maybe the policy problem list should be within a div)

**Comment by rezzo** [comment]
Same issue with the delete button in this view.

**Comment by jdgarrido** [comment]
half resolved

**Comment by maugsbur** [comment]
New desing on the way!
