### ISSUE TITLE
conectar vista proyecto publico a no-contribuyentes

### ISSUE THREAD

**Issue by rezzo** [ciudadanointeligente/vizard#479]

**Comment by jdgarrido** [comment]
que significa esto?

**Comment by rezzo** [comment]
no recuerdo bien, creo que era que la vista (ejemplo):
http://localhost:3000/projects/1#overview
pudiera ser visualizada por un guest. 

Pero no cacho si es prioridad y/o haya cambiado la necesidad.

**Comment by jdgarrido** [comment]
ah si, @maugsbur lo dejó listo.
